name: fittalk

services:

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5002:5002"
    networks:
      - fittalk-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    networks:
      - fittalk-network
    depends_on:
      - api
    
  meddygpt:
      build: 
        context: ./meddy_gpt
        dockerfile: Dockerfile
      restart: unless-stopped
      env_file: ./meddy_gpt/.env
      ports:
      - "8080:8080"
      volumes:
        - ./meddy_gpt:/app
        - /app/node_modules
      networks:
        - fittalk-network
      depends_on:
        - api
        - frontend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fittalk-network
    depends_on:
      - api
      - frontend
      - meddygpt


volumes:
  api_data:
  caddy_data:
  caddy_config:
networks:
  fittalk-network:
    driver: bridge
