name: fittalk

services:

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - fittalk-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - fittalk-network
    depends_on:
      - api
    
  meddygpt:
      build: 
        context: ./meddy_gpt
        dockerfile: Dockerfile
      restart: unless-stopped
      env_file: ./meddy_gpt/.env
      ports:
      - "8080:8080"
      volumes:
        - ./meddy_gpt:/app
        - /app/node_modules
      networks:
        - fittalk-network
      depends_on:
        - api
        - frontend

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - fittalk-network
    depends_on:
      - api
      - frontend
      - meddygpt


volumes:
  api_data:
  caddy_data:
  caddy_config:
networks:
  fittalk-network:
    driver: bridge
