apiVersion: v1
kind: Pod
metadata:
  name: secret-sync-debug
spec:
  serviceAccountName: secrets-store-sa
  containers:
  - name: test
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "fittalk-api-secrets"
