apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fittalk-api-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "fit-talk/backend-secrets"
        objectType: "secretsmanager"
    region: "eu-west-2"
  secretObjects:
    - secretName: backend-secrets-sync
      type: Opaque
      data:
        - objectName: MONGODB_URI
          key: MONGODB_URI
        - objectName: API_PORT
          key: API_PORT
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: BOT_USER_ID
          key: BOT_USER_ID
        - objectName: FLASK_API_URL
          key: FLASK_API_URL
        - objectName: CLOUDINARY_CLOUD_NAME
          key: CLOUDINARY_CLOUD_NAME
        - objectName: CLOUDINARY_API_KEY
          key: CLOUDINARY_API_KEY
        - objectName: CLOUDINARY_API_SECRET
          key: CLOUDINARY_API_SECRET
        - objectName: ORIGIN
          key: ORIGIN
        - objectName: MEDDY_AUTH_API_KEY
          key: MEDDY_AUTH_API_KEY
        - objectName: NODE_ENV
          key: NODE_ENV
