apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: frontend-secrets-provider
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "fit-talk/frontend-secrets"
        objectType: "secretsmanager"
    region: "eu-west-2"
  secretObjects:
    - secretName: frontend-secrets
      type: Opaque
      data:
        - objectName: VITE_API_URL
          key: VITE_API_URL
        - objectName: MODE
          key: MODE
        - objectName: DOMAIN_NAME
          key: DOMAIN_NAME
