apiVersion: v1
kind: Secret
metadata:
  name: meddygpt-secrets
type: Opaque
stringData:
  PINECONE_API_KEY: "$PINECONE_API_KEY"
  OPENAI_API_KEY: "$OPENAI_API_KEY"
  FLASK_ENV: "$FLASK_ENV"
  DEBUG: "$DEBUG"
  FRONTEND_ORIGIN: "$FRONTEND_ORIGIN"
  MEDDY_AUTH_API_KEY: "$MEDDY_AUTH_API_KEY"
  LANGCHAIN_TRACING_V2: "$LANGCHAIN_TRACING_V2"